# Generated by Django 5.0.2 on 2024-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
