# Generated by Django 5.0.2 on 2024-02-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
