# Generated by Django 5.0.2 on 2024-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_flight_departure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airport',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
