# Generated by Django 5.0.2 on 2024-02-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_flight_airport_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
