# Generated by Django 5.0.2 on 2024-03-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
