# Generated by Django 5.0.2 on 2024-03-31 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.ForeignKey(default='1',on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
