# Generated by Django 5.0.2 on 2024-03-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_booking_status_alter_booking_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
