# Generated by Django 5.0.2 on 2024-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingCost',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
