# Generated by Django 5.0.2 on 2024-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_booking_bookingcost_alter_booking_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
