# Generated by Django 5.0.2 on 2024-04-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
